settings:
  talkInStaffChat: '!'
  banMessage: '&cYou cannot join as you have been banned for: \n%reason%'
  kickOnWarn: true
  database:
    hostname: '127.0.0.1'
    port: 3306
    database: core
    username: root
    password: Mebra2134