settings:
  talkInStaffChat: '!'
  banMessage: '&cYou cannot join as you have been banned for: \n%reason%'
  kickOnWarn: true
  database:
    hostname: tropicalhost.nl
    port: 3306
    database: mininetw_tbungee
    username: mininetw_tbungee
    password: Trilar2018